### ISSUE TITLE
This tool has the file transfer feature?Can you provide a file transfer sample?

### ISSUE THREAD

**Issue by dabiaoge** [scottkiss/gosshtool#2]
This tool has the file transfer feature?Can you provide a file transfer sample? Thank you !

**Comment by scottkiss** [comment]
@dabiaoge Thank for your issue,the feature do not support in this version now,the next version will add the feature.

**Comment by scottkiss** [comment]
@dabiaoge support now ,see example : [file upload example](https://github.com/scottkiss/gosshtool/blob/master/examples/filetransfer.go)

**Comment by dabiaoge** [comment]
Thank you！
